# Generated by Django 3.0 on 2019-12-18 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_title', models.TextField()),
                ('firm_representative', models.TextField()),
                ('firm_phone_number', models.TextField()),
                ('firm_email', models.TextField()),
                ('firm_address', models.TextField()),
                ('firm_services', models.TextField()),
                ('firm_mobile_number', models.TextField()),
            ],
        ),
    ]
