# Generated by Django 3.0 on 2019-12-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sautekfirm3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_title', models.TextField(blank=True, null=True)),
                ('firm_representative', models.TextField(blank=True, null=True)),
                ('firm_phone_number', models.TextField(blank=True, null=True)),
                ('firm_email', models.TextField(blank=True, null=True)),
                ('firm_address', models.TextField(blank=True, null=True)),
                ('firm_services', models.TextField(blank=True, null=True)),
                ('firm_mobile_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sautekfirm3',
                'managed': True,
            },
        ),
    ]
